import { STAR_ROAD, QUESTS, QUEST_BONUS, chapterReward } from '/home/user/oneshotgame/src/meta/progression';
import { CALENDAR } from '/home/user/oneshotgame/src/meta/calendar';
import { EVENT_TIERS } from '/home/user/oneshotgame/src/meta/events';
import { VOYAGE_REWARDS } from '/home/user/oneshotgame/src/meta/voyage';
import { FESTIVAL_TIERS } from '/home/user/oneshotgame/src/meta/festivals';
import { STICKERS, ALBUM_PAGES } from '/home/user/oneshotgame/src/meta/stickers';
import { CONSTELLATIONS } from '/home/user/oneshotgame/src/meta/constellations';
import { HABITATS } from '/home/user/oneshotgame/src/meta/habitats';
import { COSMETICS } from '/home/user/oneshotgame/src/meta/cosmetics';
import { BUILDINGS, buildCost, RING_COST, RESIDENT_ACCS, PAINTS, MAX_LEVEL } from '/home/user/oneshotgame/src/meta/homeworld';
import { rankReward } from '/home/user/oneshotgame/src/meta/rank';
import { SKINS, UPGRADES, BOOSTERS, PRODUCTS } from '/home/user/oneshotgame/src/meta/config';
import { LAB_COST } from '/home/user/oneshotgame/src/meta/lab';
import { SPECIES } from '/home/user/oneshotgame/src/core/world';

const sumR = (rs: any[]) => rs.reduce((a, r) => ({ gems: a.gems + (r.gems ?? 0), dust: a.dust + (r.dust ?? 0), b: a.b + Object.values(r.boosters ?? {}).reduce((x: number, y: any) => x + y, 0) }), { gems: 0, dust: 0, b: 0 });
it('catalog', () => {
  const out: any = {};
  out.roadFree = sumR(STAR_ROAD.map((t) => t.reward));
  out.roadPass = sumR(STAR_ROAD.map((t) => t.pass));
  out.calendar28 = sumR(CALENDAR);
  out.eventWeek = sumR(EVENT_TIERS.map((t) => t.reward));
  out.voyageWeek = sumR(VOYAGE_REWARDS);
  out.festMonth = sumR(FESTIVAL_TIERS.map((t) => t.reward));
  out.quests3avg = { gemsAvgEach: QUESTS.reduce((a, q) => a + q.gems, 0) / QUESTS.length, n: QUESTS.length, bonus: QUEST_BONUS };
  out.habitats = sumR(HABITATS.map((h) => h.reward));
  out.constellations = sumR(CONSTELLATIONS.map((c) => c.reward));
  out.constMatTotal = CONSTELLATIONS.flatMap((c) => c.bundles).reduce((a: any, b: any) => { for (const [k, v] of Object.entries(b.need)) a[k] = (a[k] ?? 0) + (v as number); return a; }, {});
  out.album = { pages: sumR(ALBUM_PAGES.map((p) => p.reward)), stickers: STICKERS.length, milestoneGems: Math.floor(STICKERS.length / 10) * 10 };
  out.ranks1to20 = sumR(Array.from({ length: 20 }, (_, i) => rankReward(i + 1)));
  out.ranks1to8 = sumR(Array.from({ length: 8 }, (_, i) => rankReward(i + 1)));
  out.chapters1to12 = sumR(Array.from({ length: 12 }, (_, i) => chapterReward(i + 1)));
  out.chapters1to3 = sumR(Array.from({ length: 3 }, (_, i) => chapterReward(i + 1)));
  // sinks
  out.cosmeticsGemSinkTotal = COSMETICS.filter((c) => c.source === 'gems').reduce((a, c) => a + (c.gems ?? 0), 0);
  out.cosmeticsBySource = COSMETICS.reduce((a: any, c) => { a[c.source] = (a[c.source] ?? 0) + 1; return a; }, {});
  out.skinsGem = SKINS.reduce((a, s) => a + s.gems, 0);
  out.paintsGem = PAINTS.reduce((a, p) => a + (p.gems ?? 0), 0);
  out.accsGem = RESIDENT_ACCS.reduce((a, p) => a + (p.gems ?? 0), 0);
  out.labPerKind = LAB_COST.reduce((a, b) => a + b, 0); out.labAll6 = out.labPerKind * 6;
  out.galaxyUpgrades = Object.fromEntries(Object.entries(UPGRADES).map(([k, u]: any) => [k, u.costs.reduce((a: number, b: number) => a + b, 0)]));
  out.ringTotal = RING_COST.reduce((a, b) => a + b, 0);
  const bl = (t: string) => { let s = 0; for (let l = 1; l <= MAX_LEVEL; l++) s += buildCost(t as any, l); return s; };
  out.buildingFullCost = Object.fromEntries(Object.entries(BUILDINGS).map(([k, d]: any) => [k, { perUnit: d.decor ? (d.gems ? `gems ${d.gems}` : d.cost) : bl(k), max: d.max, total: d.decor ? (d.gems ?? d.cost * d.max) : bl(k) * d.max }]));
  out.buildingsDustTotal = Object.entries(BUILDINGS).reduce((a: number, [k, d]: any) => a + (d.gems ? 0 : (d.decor ? d.cost * d.max : bl(k) * d.max)), 0);
  out.species = SPECIES.length; out.speciesRarity = SPECIES.reduce((a: any, s) => { a[s.rarity] = (a[s.rarity] ?? 0) + 1; return a; }, {});
  out.gemPerDollar = PRODUCTS.filter((p) => p.gems > 0 && p.consumable).map((p) => ({ k: p.key, gems: p.gems, price: p.fallbackPrice, gemsPerUSD: +(p.gems / parseFloat(p.fallbackPrice.slice(1))).toFixed(1) }));
  out.boosterDustPerGem = Object.entries(BOOSTERS).map(([k, b]) => ({ k, dust: b.dust, gems: b.gems, ratio: +(b.dust / b.gems).toFixed(1) }));
  console.log(JSON.stringify(out, null, 1));
});
