import { expect, it } from 'vitest';
import {
  PRODUCTS,
  BOOSTERS,
  UPGRADES,
  SKINS,
  STAR_ROAD,
  QUESTS,
  QUEST_BONUS,
  CALENDAR,
  VOYAGE_REWARDS,
  FESTIVAL_TIERS,
  EVENT_TIERS,
  BUILDINGS,
  BUILD_TIME,
  RING_COST,
  DYES,
  CONSTELLATIONS,
  WIN_REWARD,
  DAILY_REWARD,
  RUSH_REWARD,
  CHALLENGE_REWARD,
  LAB_COST,
  CONTINUE_COST,
  WELCOME_BACK_GEMS,
  COSMETICS,
  HABITATS,
  ALBUM_PAGES,
  MILESTONE_REWARD,
  RESIDENT_ACCS,
  PAINTS,
  BOSS_REWARD,
  COST_K,
  RATE,
  BASE_CAP_HOURS,
  DEBRIS_DUST,
  CHAPTER_REWARD,
  CHAPTER_RANK_REWARD,
  WISH_REWARD,
  CALENDAR_REPEAT_ITEM_GEMS,
  FINISH_DUST_PER_THROW,
  VISITOR_DUST,
  FRIENDSHIP_REWARD_GEMS_PER_LEVEL,
  FRIENDSHIP_TREAT,
  EXPEDITION_REWARD,
  GALAXY_RATE,
  INBOX_GIFTS,
} from '../src/meta/tuning';

function total(value: unknown): number {
  if (typeof value === 'number') return value;
  if (Array.isArray(value)) return value.reduce((sum: number, x) => sum + total(x), 0);
  if (value && typeof value === 'object') return Object.values(value).reduce((sum: number, x) => sum + total(x), 0);
  return 0;
}

it('pins totals of every central balance table', () => {
  const totals = Object.fromEntries(
    Object.entries({
      PRODUCTS,
      BOOSTERS,
      UPGRADES,
      SKINS,
      STAR_ROAD,
      QUESTS,
      QUEST_BONUS,
      CALENDAR,
      VOYAGE_REWARDS,
      FESTIVAL_TIERS,
      EVENT_TIERS,
      BUILDINGS,
      BUILD_TIME,
      RING_COST,
      DYES,
      CONSTELLATIONS,
      WIN_REWARD,
      DAILY_REWARD,
      RUSH_REWARD,
      CHALLENGE_REWARD,
      LAB_COST,
      CONTINUE_COST,
      WELCOME_BACK_GEMS,
      COSMETICS,
      HABITATS,
      ALBUM_PAGES,
      MILESTONE_REWARD,
      RESIDENT_ACCS,
      PAINTS,
      BOSS_REWARD,
      COST_K,
      RATE,
      BASE_CAP_HOURS,
      DEBRIS_DUST,
      CHAPTER_REWARD,
      CHAPTER_RANK_REWARD,
      WISH_REWARD,
      CALENDAR_REPEAT_ITEM_GEMS,
      FINISH_DUST_PER_THROW,
      VISITOR_DUST,
      FRIENDSHIP_REWARD_GEMS_PER_LEVEL,
      FRIENDSHIP_TREAT,
      EXPEDITION_REWARD,
      GALAXY_RATE,
      INBOX_GIFTS,
    }).map(([key, value]) => [key, total(value)]),
  );
  totals.PRODUCT_PRICE_CENTS = PRODUCTS.reduce((sum, product) => sum + Math.round(Number(product.fallbackPrice.slice(1)) * 100), 0);
  expect(totals).toMatchInlineSnapshot(`
    {
      "ALBUM_PAGES": 300,
      "BASE_CAP_HOURS": 6,
      "BOOSTERS": 510,
      "BOSS_REWARD": 530,
      "BUILDINGS": 12346,
      "BUILD_TIME": 23730000,
      "CALENDAR": 4950,
      "CALENDAR_REPEAT_ITEM_GEMS": 40,
      "CHALLENGE_REWARD": 60,
      "CHAPTER_RANK_REWARD": 5565,
      "CHAPTER_REWARD": 230,
      "CONSTELLATIONS": 855.75,
      "CONTINUE_COST": 50,
      "COSMETICS": 1567,
      "COST_K": 53.5,
      "DAILY_REWARD": 10,
      "DEBRIS_DUST": 60,
      "DYES": 84,
      "EVENT_TIERS": 1679,
      "EXPEDITION_REWARD": 140,
      "FESTIVAL_TIERS": 865,
      "FINISH_DUST_PER_THROW": 15,
      "FRIENDSHIP_REWARD_GEMS_PER_LEVEL": 5,
      "FRIENDSHIP_TREAT": 70,
      "GALAXY_RATE": 11,
      "HABITATS": 4515,
      "INBOX_GIFTS": 712,
      "LAB_COST": 11600,
      "MILESTONE_REWARD": 10,
      "PAINTS": 510,
      "PRODUCTS": 4580,
      "PRODUCT_PRICE_CENTS": 4493,
      "QUESTS": 175,
      "QUEST_BONUS": 21,
      "RATE": 612.5857142857143,
      "RESIDENT_ACCS": 94,
      "RING_COST": 48500,
      "RUSH_REWARD": 5.6,
      "SKINS": 450,
      "STAR_ROAD": 12584,
      "UPGRADES": 15850,
      "VISITOR_DUST": 180,
      "VOYAGE_REWARDS": 1697,
      "WELCOME_BACK_GEMS": 30,
      "WIN_REWARD": 87,
      "WISH_REWARD": 78,
    }
  `);
});
